version: "3.7"
services:
  pia:
    build: https://github.com/qdm12/private-internet-access-docker.git
    image: qmcgaw/private-internet-access
    container_name: pia
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    network_mode: bridge
    ports:
      - 8112:8112
      - 58846:58846
    init: true
    environment:
      - USER=${PIA_USER}
      - PASSWORD=${PIA_PASSWORD}
      - ENCRYPTION=strong
      - PROTOCOL=udp
      - REGION=US East
      - NONROOT=no
      - DOT=on
      - BLOCK_MALICIOUS=on
      - BLOCK_NSA=off
      - UNBLOCK=
      - FIREWALL=on
      - EXTRA_SUBNETS=
      - TINYPROXY=on
      - TINYPROXY_LOG=Critical
      - TINYPROXY_USER=
      - TINYPROXY_PASSWORD=
    restart: always
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New York
      - UMASK_SET=022 #optional
    volumes:
      - ~/.media/config/sonarr:/config
      - ~/.media/tvseries:/tv
      - ~/.media/downloads:/downloads
    network_mode: host
    ports:
      - 8989:8989
    restart: unless-stopped
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./proxy-control.conf:/etc/nginx/proxy-control.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
    network_mode: host
    ports:
      - 80:80
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: "service:pia"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=timezone
      - DELUGE_LOGLEVEL=info
    volumes:
      - ~/.media/config/deluge:/config
      - ~/.media/downloads:/downloads
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ~/.media/config/jackett:/config
      - ~/.media/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
