version: "3.7"
services:
  pia:
    build: https://github.com/qdm12/private-internet-access-docker.git
    image: qmcgaw/private-internet-access
    container_name: pia
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    network_mode: bridge
    init: true
    ports:
      - 8989:8989 # Sonarr
      - 80:80
    environment:
      - USER=${PIA_USER}
      - PASSWORD=${PIA_PASSWORD}
      - ENCRYPTION=strong
      - PROTOCOL=udp
      - REGION=US East
      - NONROOT=no
      - DOT=on
      - BLOCK_MALICIOUS=on
      - BLOCK_NSA=off
      - UNBLOCK=
      - FIREWALL=on
      - EXTRA_SUBNETS=
      #- PORT_FORWARDING=on
      - TINYPROXY=on
      - TINYPROXY_LOG=Critical
      - TINYPROXY_USER=
      - TINYPROXY_PASSWORD=
        #- SHADOWSOCKS=on
        #- SHADOWSOCKS_LOG=on
        #- SHADOWSOCKS_PASSWORD=
    restart: always
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New York
      - UMASK_SET=022 #optional
    volumes:
      - ~/.media/config:/config
      - ~/.media/tvseries:/tv
      - ~/.media/downloads:/downloads
    network_mode: "service:pia"
    restart: unless-stopped
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
    network_mode: "service:pia"
